[build-system]
requires = [
    "setuptools>=42"
    "wheel
]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q --strict-markers"
testpaths = [
    "tests"
]
python_functions = ["test"]
loglevel = "INFO"
xfail_strict = true

[tool.black]
target-version = ['py36']
